server:
  name: auth-service
  host: 192.168.0.108
  port: 10701
  grpc_port: 10801

consul:
  enabled: true
  address: http://127.0.0.1:8500

log:
  level: info

cors:
  enabled: false
  allowed_origins:
    - "*"

db:
  driver: mysql
  dsn: root:123456@tcp(127.0.0.1:3306)/aevo_db?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime_seconds: 3600
  conn_max_idle_time_seconds: 1800

redis:
  # 支持模式：
  # - standalone：单机模式
  # - sentinel：哨兵模式
  # - cluster：集群模式
  mode: standalone
  address: 127.0.0.1:6379
  password: ""

  # 哨兵模式示例：
  # mode: sentinel
  # master_name: mymaster
  # addresses:
  #   - 127.0.0.1:26379
  #   - 127.0.0.1:26380
  #   - 127.0.0.1:26381
  # password: ""

  # 集群模式示例：
  # mode: cluster
  # addresses:
  #   - 127.0.0.1:7000
  #   - 127.0.0.1:7001
  #   - 127.0.0.1:7002
  # password: ""

auth:
  access_token_ttl: 7200    # 单位：秒，2 小时
  refresh_token_ttl: 604800 # 单位：秒，7 天
  email_ttl: 300            # 单位：秒，5 分钟
  excludes:
    - /api/v1/auth/ping
    - /api/swagger.json
    - /api/v1/auth/register
    - /api/v1/auth/login
    - /api/v1/auth/reset-password
    - /api/v1/auth/refresh
    - /api/v1/auth/email/code
    - /api/v1/auth/authorize
    - /api/v1/auth/callback
    - /api/v1/auth/public-key
    - /api/v1/auth/passkey/login/begin
    - /api/v1/auth/passkey/login/finish

xss:
  enabled: true
  excludes:
    - /api/v1/content/article/*
    - /api/v1/auth/passkey/register/finish
    - /api/v1/auth/passkey/login/finish

webauthn:
  rp_id: localhost
  rp_origins:
    - http://localhost:5173
  rp_name: Aevons Admin
